### ISSUE TITLE
Invalid json should be promoted to caller.

### ISSUE THREAD

**Issue by PeterWinzell** [PeterWinzell/GDP-melco#2]
```
if(!isValidJson()){
        if(m_debug) qDebug() << "json invalid";
        **request = new VISSRequest();
        return;**
    }

    jsonObject = jsonDocument.object();

    if(!validateAction()){
        if(m_debug) qDebug() << "action invalid";
        request = new VISSRequest();
        return;
    }
    if(!validateId()){
        if(m_debug) qDebug() << "requestId invalid";
        request = new VISSRequest();
        return;
    }
```

How is the the invalid json structure being transfered to the caller/owner or the parser ? The VISSRequest does not contain any data.

**Comment by PetherPettersson** [comment]
Currently a string that fails to be parsed will not be saved in the request or the parser. As we are unable to be sure to know that there is any information available at all in the string i didn't see the need to keep this in the objects somewhere. The information is still available in W3CServer::processTextMessage(...) and can be used from in an errorhandler. 
Other solutions could be to keep the string in the parser, this would require the parser to be alive longer than just to parse the request, or in the request, but this would mean it keeps both the parsed json object and the source string if it's valid. But we can kill off the parser and don't need to worry about extra parameters to the errorhandler.
